services:
  - type: web
    name: ollama-mistral-server
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: PORT
        value: 3000
      - key: OLLAMA_HOST
        value: 0.0.0.0:11434